name: CI
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install pandoc...
        run: sudo apt-get install pandoc
      
      - name: Compile site...
        run: ./compile.sh
