name: CI
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install pandoc...
        run: sudo apt-get install pandoc
      
      - name: Compile site...
        run: ./compile.sh
    
      - name: FTP upload
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.fajtai.hu
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: public_html/pandoc/
